services:
  readonly:
    image: amamata/asi-scala-node:latest
    user: root
    networks:
      - devnet
    container_name: observer
    command:
    - run
    - --host=$OBSERVER_HOST
    - --bootstrap=rnode://$BOOTSTRAP_NODE_ID@$BOOTSTRAP_HOST?protocol=40400&discovery=40404
    - -Dlogback.configurationFile=/var/lib/rnode/logback.xml
    ports:
      - "40400:40400"
      - "40401:40401"
      - "40402:40402"
      - "40403:40403"
      - "40404:40404"
      - "40405:40405"
    volumes:
      - ./genesis/wallets.txt:/var/lib/rnode/genesis/wallets.txt
      - ./genesis/bonds.txt:/var/lib/rnode/genesis/bonds.txt
      - ./conf/observer.conf:/var/lib/rnode/rnode.conf
      - ./conf/logback.xml:/var/lib/rnode/logback.xml


networks:
  devnet:
    external: false
    name: devnet
