version: '3.8'

services:
  metrics-exporter:
    image: f1r3fly-metrics-exporter
    container_name: metrics-exporter
    restart: always
    ports:
      - "9091:9091"
    networks:
      - docker_f1r3fly

networks:
  docker_f1r3fly:
    external: true